import { MatchState } from "@/types/game";

export const initialMatchState: MatchState = {
  id: "match-olympia-final-2026",
  title: "CHUNG KẾT ĐƯỜNG LÊN ĐỈNH TRI THỨC",
  status: "active",
  current_round_index: 0,
  current_question_index: 0,
  is_timer_running: false,
  time_left: 15,
  is_locked: false,
  is_revealed: false,
  is_scored: false,
  buzzer_winner_slot: null,
  buzzer_winner_time_ms: null,
  players: [
    {
      id: "p1",
      slot_number: 1,
      name: "Nguyễn Hoàng Nam",
      school_name: "THPT Chuyên Hà Nội - Amsterdam",
      avatar_url: "https://api.dicebear.com/7.x/bottts/svg?seed=Nam",
      score: 0,
      is_connected: true,
    },
    {
      id: "p2",
      slot_number: 2,
      name: "Trần Thu Hà",
      school_name: "THPT Chuyên Lê Hồng Phong (TP.HCM)",
      avatar_url: "https://api.dicebear.com/7.x/bottts/svg?seed=Ha",
      score: 0,
      is_connected: true,
    },
    {
      id: "p3",
      slot_number: 3,
      name: "Lê Minh Quân",
      school_name: "THPT Chuyên Quốc Học Huế",
      avatar_url: "https://api.dicebear.com/7.x/bottts/svg?seed=Quan",
      score: 0,
      is_connected: true,
    },
    {
      id: "p4",
      slot_number: 4,
      name: "Phạm Thảo Vy",
      school_name: "THPT Chuyên Phan Bội Châu (Nghệ An)",
      avatar_url: "https://api.dicebear.com/7.x/bottts/svg?seed=Vy",
      score: 0,
      is_connected: true,
    },
  ],
  rounds: [
    {
      id: "r1",
      round_type: "khoi_dong",
      title: "VÒNG 1: KHỞI ĐỘNG",
      order_index: 0,
      description: "Trả lời nhanh câu hỏi trắc nghiệm / ngắn trong 15 giây. Đúng được +10 điểm, Sai 0 điểm.",
      questions: [
        {
          id: "q1_1",
          order_index: 0,
          question_text: "Tác phẩm 'Bình Ngô đại cáo' được Nguyễn Trãi viết sau chiến thắng chống lại quân xâm lược nào?",
          question_type: "multiple_choice",
          options: [
            "A. Quân Nam Hán",
            "B. Quân Nguyên Mông",
            "C. Quân Minh",
            "D. Quân Thanh",
          ],
          correct_answer: "C. Quân Minh",
          explanation: "Bình Ngô đại cáo được công bố năm 1428 sau khi nghĩa quân Lam Sơn toàn thắng quân Minh.",
          time_limit: 15,
          points_correct: 10,
          points_wrong: 0,
        },
        {
          id: "q1_2",
          order_index: 1,
          question_text: "Hành tinh nào trong Hệ Mặt Trời có nhiệt độ bề mặt trung bình cao nhất?",
          question_type: "multiple_choice",
          options: [
            "A. Sao Thủy (Mercury)",
            "B. Sao Kim (Venus)",
            "C. Sao Hỏa (Mars)",
            "D. Sao Mộc (Jupiter)",
          ],
          correct_answer: "B. Sao Kim (Venus)",
          explanation: "Sao Kim có hiệu ứng nhà kính dày đặc giữ nhiệt độ khoảng 465°C, cao hơn cả Sao Thủy.",
          time_limit: 15,
          points_correct: 10,
          points_wrong: 0,
        },
      ],
    },
    {
      id: "r2",
      round_type: "vcnv",
      title: "VÒNG 2: VƯỢT CHƯỚNG NGẠI VẬT",
      order_index: 1,
      description: "Giải mã từ khóa chướng ngại vật gồm 8 chữ cái thông qua 4 hàng ngang gợi ý.",
      config: {
        cnv_keyword: "VIỆT NAM",
        cnv_image_url: "https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1000&auto=format&fit=crop",
      },
      questions: [
        {
          id: "q2_1",
          order_index: 0,
          question_text: "Hàng ngang 1 (7 chữ cái): Quốc hoa của Việt Nam là loài hoa nào?",
          question_type: "text_input",
          correct_answer: "HOA SEN",
          explanation: "Hoa sen tượng trưng cho vẻ đẹp thanh cao, thuần khiết và bất khuất.",
          time_limit: 20,
          points_correct: 10,
          points_wrong: 0,
        },
        {
          id: "q2_2",
          order_index: 1,
          question_text: "Hàng ngang 2 (8 chữ cái): Đỉnh núi cao nhất Việt Nam và Đông Dương có tên là gì?",
          question_type: "text_input",
          correct_answer: "FANSIPAN",
          explanation: "Fansipan cao 3.143m tại thị xã Sa Pa, Lào Cai.",
          time_limit: 20,
          points_correct: 10,
          points_wrong: 0,
        },
      ],
    },
    {
      id: "r3",
      round_type: "tang_toc",
      title: "VÒNG 3: TĂNG TỐC",
      order_index: 2,
      description: "4 thí sinh cùng nhập đáp án nhanh nhất. Người đúng nhanh nhất được +40đ, kế tiếp +30đ, +20đ, +10đ.",
      questions: [
        {
          id: "q3_1",
          order_index: 0,
          question_text: "Sắp xếp các chữ cái sau thành tên một thành phố biển nổi tiếng của Việt Nam: 'A - H - N - T - R - N - G'",
          question_type: "text_input",
          correct_answer: "NHA TRANG",
          explanation: "Nha Trang - thành phố biển thuộc tỉnh Khánh Hòa.",
          time_limit: 30,
          points_correct: 40,
          points_wrong: 0,
        },
        {
          id: "q3_2",
          order_index: 1,
          question_text: "Hình tam giác có độ dài 3 cạnh lần lượt là 3cm, 4cm, 5cm. Diện tích của tam giác đó là bao nhiêu cm²?",
          question_type: "text_input",
          correct_answer: "6",
          explanation: "Đây là tam giác vuông (3² + 4² = 5²). Diện tích = (3 x 4) / 2 = 6 cm².",
          time_limit: 30,
          points_correct: 40,
          points_wrong: 0,
        },
      ],
    },
    {
      id: "r4",
      round_type: "ve_dich",
      title: "VÒNG 4: VỀ ĐÍCH",
      order_index: 3,
      description: "Thí sinh chọn gói câu hỏi, có quyền đặt Ngôi sao hy vọng. Thí sinh khác có quyền bấm chuông giành quyền.",
      questions: [
        {
          id: "q4_1",
          order_index: 0,
          question_text: "Ai là tác giả của 'Quốc ca Việt Nam' (bài hát Tiến quân ca)? (Bấm chuông giành quyền)",
          question_type: "buzzer",
          correct_answer: "Văn Cao",
          explanation: "Nhạc sĩ Văn Cao sáng tác bài hát Tiến quân ca vào năm 1944.",
          time_limit: 20,
          points_correct: 30,
          points_wrong: 15,
        },
        {
          id: "q4_2",
          order_index: 1,
          question_text: "Năm 1911, Nguyễn Tất Thành ra đi tìm đường cứu nước tại bến cảng nào?",
          question_type: "buzzer",
          correct_answer: "Bến Nhà Rồng",
          explanation: "Ngày 5/6/1911 từ Bến cảng Nhà Rồng (Sài Gòn) trên con tàu Amiral Latouche-Tréville.",
          time_limit: 20,
          points_correct: 30,
          points_wrong: 15,
        },
      ],
    },
  ],
  current_responses: {},
};
