import { MatchState } from "@/types/game";

export const initialMatchState: MatchState = {
  id: "match_olympia_2026",
  title: "Vòng Chung Kết - Đấu Trí Arena",
  is_standby: true, // Mặc định ở màn hình chờ sân khấu
  current_round_index: 0,
  current_question_index: 0,
  is_timer_running: false,
  time_left: 15,
  is_locked: false,
  is_revealed: false,
  is_scored: false,
  buzzer_winner_slot: null,
  buzzer_winner_time_ms: null, star_of_hope_slot: null, active_player_slot: null,
  players: [
    { slot_number: 1, name: "Thí sinh 1", school_name: "THPT Chuyên Hà Nội", score: 0, pin_code: "1111" },
    { slot_number: 2, name: "Thí sinh 2", school_name: "THPT Chuyên Lam Sơn", score: 0, pin_code: "2222" },
    { slot_number: 3, name: "Thí sinh 3", school_name: "THPT Chuyên Quốc Học", score: 0, pin_code: "3333" },
    { slot_number: 4, name: "Thí sinh 4", school_name: "THPT Chuyên Lê Hồng Phong", score: 0, pin_code: "4444" },
  ],
  rounds: [
    {
      id: "round_1",
      round_type: "khoi_dong",
      title: "Vòng 1: Khởi Động",
      description: "Mỗi thí sinh trả lời nhanh các câu hỏi trắc nghiệm trong 15 giây.",
      questions: [
        {
          id: "q1_1",
          order_index: 0,
          question_text: "Thủ đô của Việt Nam là thành phố nào?",
          question_type: "multiple_choice",
          options: ["A. Hà Nội", "B. TP. Hồ Chí Minh", "C. Đà Nẵng", "D. Hải Phòng"],
          correct_answer: "A. Hà Nội",
          explanation: "Hà Nội là thủ đô của nước CHXHCN Việt Nam từ năm 1945.",
          time_limit: 15,
          points_correct: 10,
          points_wrong: 0,
        },
        {
          id: "q1_2",
          order_index: 1,
          question_text: "Nguyên tố hóa học nào có ký hiệu là 'Fe'?",
          question_type: "multiple_choice",
          options: ["A. Đồng (Cu)", "B. Sắt (Fe)", "C. Nhôm (Al)", "D. Kẽm (Zn)"],
          correct_answer: "B. Sắt (Fe)",
          explanation: "Fe là ký hiệu hóa học của Sắt (Ferrum).",
          time_limit: 15,
          points_correct: 10,
          points_wrong: 0,
        },
      ],
    },
    {
      id: "round_2",
      round_type: "vchv",
      title: "Vòng 2: Vượt Chướng Ngại Vật",
      description: "Giải mã các hàng ngang để tìm ra từ khóa bí mật gồm 8 chữ cái.",
      questions: [
        {
          id: "q2_1",
          order_index: 0,
          question_text: "Hàng ngang 1 (7 chữ cái): Hành tinh lớn nhất trong Hệ Mặt Trời là gì?",
          question_type: "text_input",
          correct_answer: "SAO MOC",
          explanation: "Sao Mộc (Jupiter) là hành tinh lớn nhất trong Hệ Mặt Trời.",
          time_limit: 15,
          points_correct: 10,
          points_wrong: 0,
        },
      ],
    },
    {
      id: "round_3",
      round_type: "tang_toc",
      title: "Vòng 3: Tăng Tốc",
      description: "4 thí sinh cùng trả lời nhanh. Điểm số tương ứng 40, 30, 20, 10 điểm theo tốc độ nộp đúng.",
      questions: [
        {
          id: "q3_1",
          order_index: 0,
          question_text: "Điền số tiếp theo vào dãy quy luật: 2, 4, 8, 16, 32, ...?",
          question_type: "text_input",
          correct_answer: "64",
          explanation: "Quy luật số sau gấp đôi số trước: 32 x 2 = 64.",
          time_limit: 30,
          points_correct: 40,
          points_wrong: 0,
        },
      ],
    },
    {
      id: "round_4",
      round_type: "ve_dich",
      title: "Vòng 4: Về Đích",
      description: "Thí sinh bấm chuông nhanh để giành quyền trả lời. Trả lời đúng cộng điểm, sai bị trừ điểm.",
      questions: [
        {
          id: "q4_1",
          order_index: 0,
          question_text: "Ai là tác giả của tác phẩm văn học 'Truyện Kiều'?",
          question_type: "buzzer",
          correct_answer: "Nguyễn Du",
          explanation: "Đại thi hào Nguyễn Du là tác giả của kiệt tác Đoạn Trường Tân Thanh (Truyện Kiều).",
          time_limit: 20,
          points_correct: 30,
          points_wrong: 15,
        },
      ],
    },
  ],
  current_responses: {},
};
